language: ruby
rvm:
- 2.2.2
notifications:
  slack:
    secure: Ey2MF3e4Masx5cqQXjKXSqdjX5dnn2PPG4vOQ/pUSx+47NGKch6Mf5vK3Y31bGApKqiG5eyQmn3oyahN8WX6EQrO1j9traY+sRBPOW8vDbI2qkbfQ8W1ceUq4gQ1GELMHLFdJw3QeoyyIWJoA9xOStCPzw675M/ziiF7PiGM8grmykOTAxSY2Lpvkn9m8a57SQWYRIKQo3HUvnwNyg7ofAS5e/0N43Vy7JLkyUEwnHHhUogyDn5rJ10muUpC0s3C5Wu10iR9/3tUvM5asM5+4CdtjdL1OdteUF5L6TZtOS46R3R9zW8zk1obKOUuc1mPnxZIX6RFV35/IJBJslkq+4oTOIlY1VxE5w7u1J2qRbqcJE/GFaxIKp3E61R3cA1pPRa8xpUFel5t1xd8mTmJ5YC46wQXMeKwRytrqdLovPoHJwVCoZdNpdGX7kz/yxIdXfWKF0efnfZgdfuNbeLIbepDWU8hglv6Y8iMgUX9UecjxlrxFKkBuuYQr2MUT2N08JQR2J5sUu7PQgrC+AVblgSgKs2ofvS67lXQTg5spDU3z0GhHJ/CcmyEWSz1mnqblEDoEgheNzIvO8JgDB0DrfbvxXq/tnKCS7gBDrldqujKvjzJWErUgx1ukzBKmGPJrENTlPe+Ut9NPM2gc9GyAm/CazQOaKc5gyLK9Y/enns=
